blank_issues_enabled: false
contact_links:
  - name: Questions & Ideas
    url: https://github.com/bluejacketblackhawk/cleanroom/discussions
    about: Have a question or want to brainstorm? Start a discussion.
